Compute the mean, standard deviation, and variance of a two dimensional random integer array along 
the second axis.

In [3]:
import numpy as np
data = np.random.randint(0,100,(3,5))
print(data)
mean = np.mean(data, axis=1)
std = np.std(data, axis=1)
var = np.var(data, axis=1)

[[ 0 44 58 62 41]
 [76 14 23 38 12]
 [61 99  3 31 74]]
